import "dotenv/config";
export const ENV={
    PORT:ENV.PORT,
    MONGO_URI:ENV.MONGO_URI,
    JWT_SECRET:ENV.JWT_SECRET,
    CLIENT_URL:ENV.CLIENT_URL,
    RESEND_API_KEY:ENV.RESEND_API_KEY,
    EMAIL_FROM:ENV.EMAIL_FROM,
    EMAIL_FROM_NAME:ENV.EMAIL_FROM_NAME,
};